// Generated by Wrangler on Wed Jun 12 2024 19:39:42 GMT+0530 (India Standard Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	SPOTIFY_CLIENT_ID: string;
	SPOTIFY_CLIENT_SECRET: string;
	GROQ_API_KEY: string;
	MY_RATE_LIMITER: any;
	AI: Ai;
}
